[project]
name = "sa-fullstack-mercado"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel Gianesini Ventura", email = "142359275+gabrielgv13@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "pgembed>=0.2.0",
    "psutil>=5.9.0",
    "psycopg[binary]>=3.3.5",
]

[project.scripts]
sa-fullstack-mercado = "sa_fullstack_mercado:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
